CREATE DATABASE `ClassPointsDB`;
USE `ClassPointsDB`

CREATE TABLE `User` (
	`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`fName` VARCHAR(255) NOT NULL,
	`lName` VARCHAR(255) NOT NULL,
	`isAdmin` BOOLEAN NOT NULL,
	`email` VARCHAR(255) NOT NULL
)